# Generated by Django 4.2 on 2026-03-22 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='saved_gigs', to=settings.AUTH_USER_MODEL),
        ),
    ]
