# Generated by Django 4.2 on 2026-03-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_listing_latitude_listing_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_images/pfp-placeholder.png', upload_to='profile_images'),
        ),
    ]
