# Generated by Django 4.2 on 2026-03-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_alter_musician_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_images/pfp-placeholder.png', upload_to='profile_images'),
        ),
    ]
