# Generated by Django 4.2 on 2026-03-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_alter_band_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='gigs.musician')),
            ],
        ),
    ]
