# Generated by Django 4.2 on 2026-03-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_medialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='bookmarked_bands',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by_musicians', to='gigs.band'),
        ),
    ]
