# Generated by Django 4.2 on 2026-03-25 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0007_musician_bookmarked_bands'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='scouted_musicians',
            field=models.ManyToManyField(blank=True, related_name='scouted_by_bands', to='gigs.musician'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='gigs.band')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='gigs.listing')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='gigs.musician')),
            ],
        ),
    ]
