# Generated by Django 4.2 on 2026-03-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_band_scouted_musicians_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='scouted_musicians',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='bookmarked_bands',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
