# Generated by Django 4.2 on 2026-03-26 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0010_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigs.band')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interests', to='gigs.musician')),
            ],
        ),
    ]
