# Generated by Django 4.2 on 2026-03-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0012_alter_band_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gigs.listing'),
        ),
    ]
